package com.nust.garageapp.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a truck vehicle entity in the database.
 * 
 * @property id The unique identifier for the truck, auto-generated by the database.
 * @property licensePlate The unique license plate number of the truck.
 * @property model The brand and model name of the truck.
 */
@Entity(
    tableName = "trucks",
    indices = [androidx.room.Index(value = ["licensePlate"], unique = true)]
)
data class Truck(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val licensePlate: String,
    val model: String
)
